format = """
$username\
$hostname\
$kubernetes\
$docker_context\
$rust\
$nodejs\
$python\
$lua\
$golang\
$package\
$fill\
$cmd_duration $jobs $time\
$line_break\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$character\
"""

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

[username]
format = '[$user]($style)'
style_user = 'bold white'
style_root = 'bold red'
disabled = false
show_always = true

[hostname]
ssh_only = false
format = ' [$hostname]($style)[$ssh_symbol]($style) '
disabled = false

[localip]
ssh_only = false
format = '@[$localipv4](bold red) '
disabled = false

[fill]
symbol = " "

[directory]
format = "📁 [$path]($style)[$read_only]($read_only_style) "
style = "blue"
read_only = " 🔒"
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bright-black"

[jobs]
format = "[$symbol]($style)"
symbol = ""
style = "bold red"
number_threshold = 1

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[time]
format = "[$time]($style)"
disabled = false
style = "bold white"

[kubernetes]
format = '[⛵ $context]($style) '
disabled = true
contexts = [
  { style = "green", context_pattern = ".*nautical-services-dev", context_alias = "nautical-services-dev" },
  { style = "yellow", context_pattern = ".*nautical-services-stg", context_alias = "nautical-services-stg" },
  { style = "red", context_pattern = ".*nautical-services-prod", context_alias = "nautical-services-prod" },
]

[docker_context]
format = '[$symbol ($context)](blue bold) '
symbol = '🐋'

[rust]
symbol = " "

[nodejs]
format = "[$symbol($version)]($style) "

[lua]
format = '[$symbol($version)]($style) '

[golang]
format = '[$symbol($version)]($style) '

[python]
format = '[${symbol} ${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = '🐍'
pyenv_version_name = true

[package]
format = "[🎁 $version](208 bold)"
