[tools]
act = "latest"
cargo = "latest"
grpcurl = "latest"
helmfile = "latest"
lua = "latest"
node = "18.20.8"
pnpm = "latest"
poetry = "latest"
python = "3.11.14"
ruby = "latest"
rust = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
xh = "latest"
yj = "latest"
yq = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
